# Copyright (C) 2013 Tom Willemsen <tom at ryuslash dot org>
#
# This file is part of CLark
#
# CLark is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CLark is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CLark. If not, see <http://www.gnu.org/licenses/>.

#+TITLE: CLark
#+STARTUP: showall

* Name

  clark - collect bookmarks on your command-line

* Synopsis

  =clark= [options] [<command> [<options> ...]]

* Description

  CLark is a bookmark collection application for the command-line. It
  is a drag being dependant on your browser or an internet connection
  to be able to collect, manage and look through your bookmarks, so
  we're breaking free... slowly.

** CLark?! What the ...?

   I've been working on this program for a long time, though not very
   intensely, and it's gone through a few names.

   At first I absolutely wanted to write it in C, and I named it
   =linkwave=. I made a little program that could store given URLs with
   names and descriptions, but not much else than that.

   Then I started messing around with Lisp and some of its
   derivatives, such as chicken scheme. And then I thought it would be
   much cooler to (re)write this in scheme! I named it =markam=, because
   Markam collects books.

   Now, I'm thinking that it would be much cooler _still_ to write the
   thing in Common Lisp! So I name it CLark, because it is Common
   Lisp, and a rewrite of mARKam.

* Options

  - =--script= :: Change the output of some commands to be somewhat more
                machine-friendly, making it easier to parse the data.

* Commands

  - =add= :: Add a new bookmark to the database.

  - =edit= :: Edit a bookmark's information.

  - =exists= :: Check if a bookmark is already present in the database.

  - =help= :: Prints a usage and help message, showing a list of
            possible commands and some hints on how to use them.

  - =remove= :: Remove a bookmark from the database.

  - =search= :: Search through the database looking for a partial match
              on its name or an exact-matching tag.

  - =set-tags= :: Replace or remove a bookmark's tags.

  - =version= :: Prints the CLark version and then quits.
